# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bandheap Blog
email: info@bandheap.com
description: > # this means to ignore newlines until "baseurl:"
  Bandheap is your source for local music and this is a blog about the
  guts of it
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bandheap.com" # the base hostname & protocol for your site
twitter_username: bandheap

# Build settings
markdown: kramdown
