# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Knock Blockers
email: band@knockblockersska.com
description: > # this means to ignore newlines until "baseurl:"
  Ska from Colorado Springs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://knockblockersska.com" # the base hostname & protocol for your site
host: 0.0.0.0

# Build settings
bandsintown:
  strftime: "%b %e"
  bands:
    - "The Knock Blockers"

gems:
  - hash-joiner

markdown: kramdown
