# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Rhythm Ratz
email: band@therhythmratz.com
description: > # this means to ignore newlines until "baseurl:"
 The Rhythm Ratz are a psychobilly and rockabilly band from Colorado Springs, CO.
 That's Ratz with a Z not Rhythm Rats.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://therhythmratz.com"
host: 0.0.0.0

# Build settings
markdown: kramdown

bandsintown:
  strftime: "%b %e"
  bands:
    - "The Rhythm Ratz"