# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy Barilla
email: me@andybarilla.com
description: The website for Andy Barilla, bass player and geek
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andybarilla.com"
host: 0.0.0.0

# Build settings
markdown: kramdown

bandsintown:
  strftime: "%b %e"
  bands:
    - "Tinker's Damn"
    - "Knock Blockers"

gems:
  - hash-joiner
